export const users = [
  {
    dni: 1,
    username: "usuario1",
    email: "usuario1@example.com",
    password: "contraseña1",
    available_money: 100.0,
  },
  {
    dni: 2,
    username: "usuario2",
    email: "usuario2@example.com",
    password: "contraseña2",
    available_money: 200.0,
  },
  {
    dni: 3,
    username: "usuario3",
    email: "usuario3@example.com",
    password: "contraseña3",
    available_money: 300.0,
  },
  {
    dni: 4,
    username: "usuario4",
    email: "usuario4@example.com",
    password: "contraseña4",
    available_money: 400.0,
  },
  {
    dni: 5,
    username: "usuario5",
    email: "usuario5@example.com",
    password: "contraseña5",
    available_money: 500.0,
  },
  {
    dni: 6,
    username: "usuario6",
    email: "usuario6@example.com",
    password: "contraseña6",
    available_money: 600.0,
  },
  {
    dni: 7,
    username: "usuario7",
    email: "usuario7@example.com",
    password: "contraseña7",
    available_money: 700.0,
  },
  {
    dni: 8,
    username: "usuario8",
    email: "usuario8@example.com",
    password: "contraseña8",
    available_money: 800.0,
  },
  {
    dni: 9,
    username: "usuario9",
    email: "usuario9@example.com",
    password: "contraseña9",
    available_money: 900.0,
  },
  {
    dni: 10,
    username: "usuario10",
    email: "usuario10@example.com",
    password: "contraseña10",
    available_money: 1000.0,
  },
  {
    dni: 11,
    username: "usuario11",
    email: "usuario11@example.com",
    password: "contraseña11",
    available_money: 1100.0,
  },
  {
    dni: 12,
    username: "usuario12",
    email: "usuario12@example.com",
    password: "contraseña12",
    available_money: 1200.0,
  },
  {
    dni: 13,
    username: "usuario13",
    email: "usuario13@example.com",
    password: "contraseña13",
    available_money: 1300.0,
  },
  {
    dni: 14,
    username: "usuario14",
    email: "usuario14@example.com",
    password: "contraseña14",
    available_money: 1400.0,
  },
  {
    dni: 15,
    username: "usuario15",
    email: "usuario15@example.com",
    password: "contraseña15",
    available_money: 1500.0,
  },
  {
    dni: 16,
    username: "usuario16",
    email: "usuario16@example.com",
    password: "contraseña16",
    available_money: 1600.0,
  },
  {
    dni: 17,
    username: "usuario17",
    email: "usuario17@example.com",
    password: "contraseña17",
    available_money: 1700.0,
  },
  {
    dni: 18,
    username: "usuario18",
    email: "usuario18@example.com",
    password: "contraseña18",
    available_money: 1800.0,
  },
  {
    dni: 19,
    username: "usuario19",
    email: "usuario19@example.com",
    password: "contraseña19",
    available_money: 1900.0,
  },
  {
    dni: 20,
    username: "usuario20",
    email: "usuario20@example.com",
    password: "contraseña20",
    available_money: 2000.0,
  },
];

// Puedes continuar agregando más usuarios si lo deseas.
